name: Strings Translation

on:
  push:
    branches: dev
    paths: strings/strings/en.yml
  workflow_dispatch:

jobs:
  analyze:
    name: Checkout Strings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Update Translations
        uses: technote-space/create-pr-action@v2
        with:
         EXECUTE_COMMANDS: |
           sudo apt-get update && sudo apt-get upgrade -y && sudo apt install wget -y
           pip install pyyaml https://github.com/TeamUltroid/pyUltroid/archive/dev.zip requests
           wget -O run.py https://gist.githubusercontent.com/New-dev0/906ba98055bf4ab0ce54d2ff8836ec5e/raw/69d417c90d2ee72f943a22a405aa0ba6a612dc92/updatetr.py
           python3 run.py && rm run.py
         COMMIT_MESSAGE: '[Auto]: update'
         COMMIT_NAME: 'GitHub Actions'
         COMMIT_EMAIL: 'TeamUltroid@ultroid.tech'
         PR_BRANCH_NAME: 'translation-update-${PR_ID}'
         PR_TITLE: '[AUTO]: Update Translations'
