name: Strings Translation

on:
  workflow_dispatch:
  push:
    branches: dev
    paths:
    - strings/strings/en.yml

jobs:
  analyze:
    name: Checkout Strings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Update Translations
        run: |
           sudo apt update && sudo apt upgrade -y && sudo apt install wget git gh -y
           git branch translation && git checkout translation && pip install pyyaml https://github.com/TeamUltroid/pyUltroid/archive/dev.zip requests
           wget -O run.py https://gist.githubusercontent.com/New-dev0/906ba98055bf4ab0ce54d2ff8836ec5e/raw/69d417c90d2ee72f943a22a405aa0ba6a612dc92/updatetr.py
           python3 run.py && rm run.py
           git add . && git commit -m "[Auto] Translate" && git push
           gh create pr --title "[Auto] Translation" -B dev
         
